### ISSUE TITLE
Do not crash outliers in case a single document can't be updated

### ISSUE THREAD

**Issue by daanraman** [NVISO-BE/ee-outliers#11]
Example error:
```

-eagleeye-%25%7B%5Bsmoky_filter_name%5D%7D-2018.10.26/doc/5SEcr2YBDK6V8tqIuxL_/_update?refresh=true [status:400 request:0.016s]
2018-10-31 10:25:00 - ERROR - Traceback (most recent call last):
  File "outliers.py", line 100, in <module>
    perform_analysis()
  File "outliers.py", line 44, in perform_analysis
    simplequery_generic.perform_analysis()
  File "/app/analyzers/simplequery_generic.py", line 20, in perform_analysis
    run_simplequery_model(section_name=name, model_name=model_name, model_settings=model_settings)
  File "/app/analyzers/simplequery_generic.py", line 77, in run_simplequery_model
    evaluate_model(model_name=model_name, model_settings=model_settings)
  File "/app/analyzers/simplequery_generic.py", line 68, in evaluate_model
    es.process_outliers(doc=doc, outliers=[outlier], should_notify= model_settings["should_notify"])
  File "/app/helpers/es.py", line 144, in process_outliers
    self.save_outlier(doc=doc, outlier=outlier)
  File "/app/helpers/es.py", line 165, in save_outlier
    self.conn.update(index=doc["_index"], doc_type=doc["_type"], id=doc["_id"], body=doc_body, refresh=True)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 547, in update
    doc_type, id, '_update'), params=params, body=body)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', '[esnode2][172.18.0.25:9300][indices:data/write/update[s]]')

2018-10-31 10:25:01 - INFO - housekeeping thread #140529569572608 stopped
2018-10-31 10:25:01 - INFO - finished performing outlier detection
2018-10-31 10:25:01 - INFO - next run scheduled on 2018-10-31 10:26:00
```

**Comment by daanraman** [comment]
More robust use case processing in 0.2.0
