### ISSUE TITLE
high number of tagged outliers results in scroll context expiring

### ISSUE THREAD

**Issue by daanraman** [NVISO-BE/ee-outliers#26]
```
2018-12-11 19:00:38 - ERROR - Traceback (most recent call last):
  File "outliers.py", line 104, in <module>
    perform_analysis()
  File "outliers.py", line 47, in perform_analysis
    metrics_generic.perform_analysis()
  File "/app/analyzers/metrics_generic.py", line 20, in perform_analysis
    run_generic_metrics_model(section_name=name, model_name=model_name, model_settings=model_settings)
  File "/app/analyzers/metrics_generic.py", line 214, in run_generic_metrics_model
    evaluate_model(model_name=model_name, model_settings=model_settings)
  File "/app/analyzers/metrics_generic.py", line 77, in evaluate_model
    for doc in es.scan(lucene_query=lucene_query):
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/helpers/__init__.py", line 379, in scan
    **scroll_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 1011, in scroll
    params=params, body=body)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'search_phase_execution_exception', 'No search context found for id [390777]')
```

**Comment by daanraman** [comment]
This is actually not a bug - only way we can deal with this:
- Have a better use case which triggers on less items
- Increase scroll timeout in configuration file
