### ISSUE TITLE
too_long_frame_exception

### ISSUE THREAD

**Issue by olivierbuez** [NVISO-BE/ee-outliers#413]
```
2019-10-01 10:22:09 - INFO - powershell_execution_hidden_window_autogenerated - evaluating simplequery model [1 eps. - 100.00% done]
W1001 10:22:09.421566 140560573461504 base.py:133] GET http://esnode1:9200/_search/scroll/DnF1ZXJ5VGhlbkZldGNogQEAAAAAAliqJxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYqioWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKooFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliqKxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYqikWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKpAFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliqQxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYqm0WZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKpuFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliqbxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYqnAWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKpyFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliqcxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYqnQWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKp2FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliqdxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYqngWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKp5FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlirGRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYqy0WZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKsxFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlirMhZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYqzsWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKtSFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlirVhZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYq1wWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKteFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlirbhZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYq3MWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKt1FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlirexZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYq38WZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKuAFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlirqRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYq6oWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKurFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlirtRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrFEWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKxSFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlisVhZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrHwWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKyqFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlissBZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrLEWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKyzFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlisuRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrMMWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKzFFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlis6hZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrOsWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKzzFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlis9BZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrPUWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKz3FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlis-BZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrPkWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKz6FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlis-xZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrP0WZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWKz-FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlitkRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrb4WZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK3EFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlit1BZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrdwWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK3qFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlit7RZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrfEWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK31FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlit-RZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrfoWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK37FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlit_RZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrgIWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK4GFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliuCBZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYri4WZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK4xFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliuNRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrkMWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK5EFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliuRRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrkcWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK5IFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliu2xZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrvwWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK8BFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlivDBZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYrxAWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK81FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlivPhZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYr0wWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK9YFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlivchZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYr3oWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK97FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlivfBZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYr30WZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK9-FmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlivfxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYr4AWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK-BFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAlivgxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYr4QWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWK-OFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliwIRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYsCwWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWLAvFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliwMBZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYsDUWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWLBGFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliwSxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYsE0WZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWLBTFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliwVRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYsFYWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWLBmFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliwbxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYsHAWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWLCcFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliwoxZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYsLUWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWLDIFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliwyRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYsMoWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWLDMFmZwMWNDQ3dEUy1HU3JKckROdnRTVXcAAAAAAliwzRZmcDFjQ0N3RFMtR1NySnJETnZ0U1V3AAAAAAJYsYUWZnAxY0NDd0RTLUdTckpyRE52dFNVdwAAAAACWLGkFmZwMWNDQ3dEUy1HU3JKckROdnRTVXc%3D?scroll=25m [status:400 request:0.001s]
2019-10-01 10:22:09 - ERROR - error while analyzing use case
Traceback (most recent call last):
  File "outliers.py", line 242, in perform_analysis
    analyzer.evaluate_model()
  File "/app/analyzers/simplequery.py", line 49, in evaluate_model
    for doc in documents:
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 458, in scan
    **scroll_kwargs
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1355, in scroll
    "GET", _make_path("_search", "scroll", scroll_id), params=params, body=body
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 236, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 162, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'too_long_frame_exception', 'An HTTP line is larger than 4096 bytes.')
```

**Comment by olivierbuez** [comment]
This is still occuring at CF
