### ISSUE TITLE
Issue model_settings=None in _get_highlight_settings() when remove_all_whitelisted_outliers() executed.

### ISSUE THREAD

**Issue by maximilienroberti** [NVISO-BE/ee-outliers#552]
```
outliers_dev | 2020-07-03 11:18:29 - INFO - housekeeping - going to remove all whitelisted outliers
outliers_dev | 2020-07-03 11:18:29 - ERROR - housekeeping - something went wrong removing whitelisted outliers
outliers_dev | Traceback (most recent call last):
outliers_dev |   File "/app/helpers/housekeeping.py", line 67, in remove_all_whitelisted_outliers
outliers_dev |     total_docs_whitelisted = es.remove_all_whitelisted_outliers(self.dict_analyzer)
outliers_dev |   File "/app/helpers/es.py", line 224, in remove_all_whitelisted_outliers
outliers_dev |     total_nr_outliers, documents = self.count_and_scan_documents(index=idx, bool_clause=outliers_filter_query)
outliers_dev |   File "/app/helpers/es.py", line 172, in count_and_scan_documents
outliers_dev |     model_settings)
outliers_dev |   File "/app/helpers/es.py", line 119, in _scan
outliers_dev |     highlight_settings = self._get_highlight_settings(model_settings)
outliers_dev |   File "/app/helpers/es.py", line 505, in _get_highlight_settings
outliers_dev |     if "highlight_match" in model_settings and model_settings["highlight_match"]:
outliers_dev | TypeError: argument of type 'NoneType' is not iterable
outliers_dev | 2020-07-03 11:18:29 - INFO - housekeeping - finished round of cleaning whitelisted items
```

**Comment by maximilienroberti** [comment]
Issue resolved on PR #553.
